version: 2.1

jobs:
  test:
    docker:
      - image: node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run: |
          
          npm install -g allure-commandline
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
      - run:
            command: |
                  apt-get -y install default-jre
                  npm install -g allure-commandline
            when: always
      - run:
            command: |
                  mvn test
                  allure generate --clean
            when: always

workflows:
  test_my_app:
    jobs:
      - test

