version: 2.1

jobs:
  test:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
            command: |
                  apt  install default-jre -y
                  apt install maven -y
                  npm install -g allure-commandline
            when: always
      - run:
            command: |
                  mvn test
                  allure generate --clean
            when: always


workflows:
  test_my_app:
    jobs:
      - test
